### ISSUE TITLE
connectionString know what to put in the fields...

### ISSUE THREAD

**Issue by runtimevic** [jh-isw/EventLoggerConnector#5]
I can't fill in all the fields, could you give an example with photos?, to know what to put in the fields...

connectionString="Server=YOURIP;port=YOURPORT;Database=YOURDB;User Id=YOURUSER;Password=YOURPASSWORD;" providerName="Npgsql"

Thank you so much, Víctor.

**Comment by jh-isw** [comment]
Here's an example that assumes a Server at IP 192.168.178.2 Port 5433 with a database named MyEvents, a postgres user named MyPostgresUser and a password MySuperSecretPassword:

```XML
<connectionStrings>
    <add name="EventsDbContext" connectionString="Server=192.168.178.2;port=5433;Database=MyEvents;User Id=MyPostgresUser;Password=MySuperSecretPassword;" providerName="Npgsql" />
  </connectionStrings>
```

Does that help?

**Comment by runtimevic** [comment]
> Here's an example that assumes a Server at IP 192.168.178.2 Port 5433 with a database named MyEvents, a postgres user named MyPostgresUser and a password MySuperSecretPassword:
> 
> ```
> <connectionStrings>
>     <add name="EventsDbContext" connectionString="Server=192.168.178.2;port=5433;Database=MyEvents;User Id=MyPostgresUser;Password=MySuperSecretPassword;" providerName="Npgsql" />
>   </connectionStrings>
> ```
> 
> Does that help?

Hi @jh-isw ,
can you export and submit your postgresql event table so you can import and create the same table with the same fields?
Best regards, Víctor.

**Comment by jh-isw** [comment]
Hi @runtimevic,
I had the DB only temporarily for testing, but I guess what you are missing is to update the database with the migration:
Build the software, so all nuget packages get fetched.
Then, from within the Visual Studio Developer console, try:
```
enable-migrations
update-database -Verbose
```

Then, you can start the application.

Did that work?
